name: Pull Request (CI)

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'app/VERSION'
      - 'app/DEPLOY'
      - '.github/workflows/merge.yml'
      - '.github/workflows/release.yml'      
    branches:
      - main

jobs:
  ci:
    uses: alice-biometrics/actions/.github/workflows/lume-ci.yml@v1.32
    with:
      language: python
      post_commands: test-property,test:e2e-local
    secrets:
      github_access_token: ${{ secrets.ALICE_GITHUB_ACCESS_TOKEN }}
      gke_project: ${{ secrets.GKE_PROJECT_STAGING }}
      gke_key: ${{ secrets.GKE_KEY_STAGING }}

